language: go

go:
  - 1.10.8

install:
  - go get k8s.io/client-go/...
  - go get -u sigs.k8s.io/kind
  - curl -LO https://storage.googleapis.com/kubernetes-release/release/v1.14.0/bin/linux/amd64/kubectl && chmod +x ./kubectl && sudo mv ./kubectl /usr/local/bin/kubectl && kubectl version
script:
  - go build ./cmd/controller/
  - go test -v  ./... -run "Unit"
  - docker run --rm -p 18332:18332 -d christianb93/bitcoind:latest
  - kind create cluster 
