language: go
dist: xenial


go:
  - 1.10.8

install:
  - go get k8s.io/client-go/...
  - go get -u sigs.k8s.io/kind

script:
  - go build ./cmd/controller/
  - go test -v  ./... -run "Unit"
  - cd cmd/controller
  - CGO_ENABLED=0 go build
  - docker build --rm -f ../../build/controller/Dockerfile -t christianb93/bitcoin-controller:latest .
