language: go
dist: xenial


go:
  - 1.10.8

install:
  - go get k8s.io/client-go/...

script:
  - go build ./cmd/controller/
  - go test -v  ./... -run "Unit"
  - ./travis/buildAndPushImage.sh

deploy:
  - echo "$DOCKER_PASSWORD" | docker login --username $DOCKER_USER --password-stdin
    tag=$(cat ./tag)
    docker push christianb93/bitcoin-controller:$tag
    docker push christianb93/bitcoin-controller:latest
