language: go
dist: xenial

env:
  - GO111MODULE=on

cache:
  directories:
    - $TRAVIS_HOME/.cache

go:
  - 1.13.6

install:
  - go get -d -t ./...

script:
  - go build ./cmd/controller/
  - go test -v  ./... -run "Unit" -count=1
  - ./travis/buildImage.sh

deploy:
  skip_cleanup: true
  provider: script
  script:  bash ./travis/deploy.sh
  on:
    all_branches: true
