language: go
dist: xenial


go:
  - 1.10.8

install:
  - go get k8s.io/client-go/...

script:
  - go build ./cmd/controller/
  - go test -v  ./... -run "Unit"
  - ./travis/buildImage.sh

deploy:
  provider: script
  script:  bash ./travis/pushImage.sh
