language: go
dist: xenial


go:
  - 1.10.8

install:
  - go get k8s.io/client-go/...

script:
  - go build ./cmd/controller/
  - go test -v  ./... -run "Unit"
  - env
  - tag=$(./travis/buildAndPushImage.sh)
  - echo "Pushed image christianb93/bitcoin-controller:$tag"
