language: go
dist: xenial

env:
  - GO111MODULE=off

go:
  - 1.10.8

install:
  - go get k8s.io/client-go/...

script:
  - go build ./cmd/controller/
  - go test -v  ./... -run "Unit"
  - ./travis/buildImage.sh

after_success:
  - sudo snap install helm --classic
  - helm init --client-only

deploy:
  skip_cleanup: true
  provider: script
  script:  bash ./travis/deploy.sh
