language: go
dist: xenial


go:
  - 1.10.8

install:
  - go get k8s.io/client-go/...
  - go get -u sigs.k8s.io/kind
  - curl -LO https://storage.googleapis.com/kubernetes-release/release/v1.14.0/bin/linux/amd64/kubectl
  - chmod +x ./kubectl && sudo mv ./kubectl /usr/local/bin/kubectl

script:
  - go build ./cmd/controller/
  - go test -v  ./... -run "Unit"
  - docker run -d -p 18332:18332 christianb93/bitcoind:v1.0
  - kind create cluster
  - export KUBECONFIG="$(kind get kubeconfig-path --name="kind")"
  - kubectl cluster-info
